config/routes.rb
Rails.application.routes.draw do

  get 'admin_pages/index'
  root :to => 'bicycles#index'
  get 'bicycles/search' => 'bicycles#search'
  resources :bicycles
  resources :styles
  devise_for :admins
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
          :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord
  validates :name, length: {minimum: 5 , maximum: 15} ,:presence => true
  validates :description, length: {minimum: 10 } ,:presence => true
  validates :price,  numericality: true ,:presence => true
  validates_associated :style
  mount_uploader :image_link , PicUploader
  belongs_to :style


  def self.search (condition,pattern)
    @conditon = condition
    where(@conditon + ' LIKE ?', "%#{pattern}%")
  end


end

app/models/style.rb
class Style < ApplicationRecord
  validates :name, length: {minimum: 5 , maximum: 15} ,:presence => true
  has_many :bicycles
end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @styles = Style.all
    @bicycles = Bicycle.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    admin_pages_index_path
  end
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  before_action :authenticate_admin! , only: [:new,:create,:edit,:update,:destroy]
  before_action :set_bicycle, only: [:show, :edit, :update, :destroy]

  # GET /bicycles
  # GET /bicycles.json
  def index
    @bicycles = Bicycle.all
  end

  # GET /bicycles/1
  # GET /bicycles/1.json
  def show
  end

  # GET /bicycles/new
  def new
    @bicycle = Bicycle.new

  end

  # GET /bicycles/1/edit
  def edit
  end

  # POST /bicycles
  # POST /bicycles.json
  def create
    @bicycle = Bicycle.new(bicycle_params)

    respond_to do |format|
      if @bicycle.save
        format.html { redirect_to admin_pages_index_path, notice: 'Bicycle was successfully created.' }
        format.json { render :show, status: :created, location: @bicycle }
      else
        format.html { render :new }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bicycles/1
  # PATCH/PUT /bicycles/1.json
  def update
    respond_to do |format|
      if @bicycle.update(bicycle_params)
        format.html { redirect_to admin_pages_index_path, notice: 'Bicycle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bicycle }
      else
        format.html { render :edit }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bicycles/1
  # DELETE /bicycles/1.json
  def destroy
    @bicycle.destroy
    respond_to do |format|
      format.html { redirect_to admin_pages_index_path, notice: 'Bicycle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @conditions = params[:conditions]

    @result = Bicycle

    if @conditions[:name] != 'true' &&  @conditions[:style] != 'true'
      @result = Bicycle.joins(:style).includes(:style).all
    end

    if @conditions[:name] == 'true'
        @result = @result.joins(:style).includes(:style).search('`bicycles`.name',params[:value][:nameText])
    end

    if @conditions[:style] == 'true'
      @result  = @result.joins(:style).includes(:style).search('`styles`.name',params[:value][:styleText])
    end

    @resultArray = []

    @result.each do |bicycle|

      @newVar = {styleName: bicycle.style.name,bicyleObj: bicycle}


      @resultArray << @newVar

    end

    respond_to do |format|
      format.json { render :json => {'result' => @resultArray } }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bicycle
      @bicycle = Bicycle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bicycle_params
      params.fetch(:bicycle, {}).permit(:name,:description,:image_link,:price,:style_id)
    end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController

  before_action :authenticate_admin! , only: [:new,:create,:edit,:update,:destroy]
  before_action :set_style, only: [:show, :edit, :update, :destroy]


  # GET /styles
  # GET /styles.json
  def index
    @styles = Style.all
  end

  # GET /styles/1
  # GET /styles/1.json
  def show
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles
  # POST /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to admin_pages_index_path, notice: 'Style was successfully created.' }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1
  # PATCH/PUT /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to admin_pages_index_path, notice: 'Style was successfully updated.' }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1
  # DELETE /styles/1.json
  def destroy
    @style.destroy
    respond_to do |format|
      format.html { redirect_to admin_pages_index_path, notice: 'Style was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_style
      @style = Style.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def style_params
      params.fetch(:style, {}).permit(:name)
    end
end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/admin_pages/_logout.html.erb
<%= link_to "User Home Page" ,"/" , :method => 'get' ,  class:  'btn btn-warning' %>
<%= link_to "Admin Home" , "/admin_pages/index" , :method => 'get' ,  class:  'btn btn-default'%>

<%= link_to "Signout" , "/admins/sign_out" , :method => 'delete' ,  class:  'btn btn-danger'%>

app/views/admin_pages/index.html.erb
<%= render 'logout' %>
<div class="container">

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Styles</div>
  <div class="panel-body">
    <%= link_to "Create" , "/styles/new" , :method => 'get' ,  class:  'btn btn-success'%>

  </div>

  <!-- Table -->
  <table class="table">
  <tr>
    <th>id</th>
    <th>name</th>
    <th>show</th>
    <th>edit</th>
    <th>delete</th>
  </tr>
    <% @styles.each do |style| %>
        <tr>
          <td><%= style.id %></td>
          <td> <%= style.name %></td>
          <td><%= link_to 'Show', style %></td>
          <td><%= link_to 'Edit', edit_style_path(style) %></td>
          <td><%= link_to 'Destroy', style, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>


  </table>
</div>
</div>

<hr>

<div class="container">

  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">bicycles</div>
    <div class="panel-body">
      <%= link_to "Create" , "/bicycles/new" , :method => 'get' ,  class:  'btn btn-success'%>
    </div>

    <!-- Table -->
    <table class="table">
      <tr>
        <th>id</th>
        <th>name</th>
        <th>price</th>
        <th>style</th>
        <th>show</th>
        <th>edit</th>
        <th>delete</th>
      </tr>
      <% @bicycles.each do |bicycle| %>
          <tr>
            <td><%= bicycle.id %></td>
            <td> <%= bicycle.name %></td>
            <td><%= number_to_currency(bicycle.price,:delimiter => ".", :separator => ",") %></td>
            <td><%= bicycle.style.name %></td>
            <td><%= link_to 'Show', bicycle %></td>
            <td><%= link_to 'Edit', edit_bicycle_path(bicycle) %></td>
            <td><%= link_to 'Destroy', bicycle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>

    </table>
  </div>
</div>

app/views/bicycles/_footer.html.erb
<!-- Support section -->
<section id="aa-support">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="aa-support-area">
          <!-- single support -->
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="aa-support-single">
              <span class="fa fa-truck"></span>
              <h4>FREE SHIPPING</h4>
              <P>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam, nobis.</P>
            </div>
          </div>
          <!-- single support -->
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="aa-support-single">
              <span class="fa fa-clock-o"></span>
              <h4>30 DAYS MONEY BACK</h4>
              <P>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam, nobis.</P>
            </div>
          </div>
          <!-- single support -->
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="aa-support-single">
              <span class="fa fa-phone"></span>
              <h4>SUPPORT 24/7</h4>
              <P>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam, nobis.</P>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- / Support section -->




<!-- footer -->
<footer id="aa-footer">

  <div class="aa-footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-footer-bottom-area">
            <p>Designed by <a href="http://www.markups.io/">MarkUps.io</a></p>
            <div class="aa-footer-payment">
              <span class="fa fa-cc-mastercard"></span>
              <span class="fa fa-cc-visa"></span>
              <span class="fa fa-paypal"></span>
              <span class="fa fa-cc-discover"></span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- / footer -->

app/views/bicycles/_form.html.erb
<%= form_for(bicycle) do |f| %>
  <% if bicycle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bicycle.errors.count, "error") %> prohibited this bicycle from being saved:</h2>

      <ul>
      <% bicycle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.label :name %>:
    <%= f.text_field :name %>
    <br>
    <br>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <br>
    <br>
    <%= f.label :price %>
    <%= f.text_field :price   %>
    <br>
    <br>

          <%= f.label :style %><br />
    <%= f.select :style_id, Style.all.collect { |s| [ s.name, s.id ] } %>

    <br> <br>
      <%= f.label :image_link , "Upload Image "%><br>
      <%= f.file_field :image_link %>
    <br> <br>
    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bicycles/_header.html.erb
<!-- SCROLL TOP BUTTON -->
<a class="scrollToTop" href="#"><i class="fa fa-chevron-up"></i></a>
<!-- END SCROLL TOP BUTTON -->


<!-- Start header section -->
<header id="aa-header">


    <!-- start header bottom  -->
    <div class="aa-header-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="aa-header-bottom-area">
                        <!-- logo  -->
                        <div class="aa-logo">
                            <!-- Text based logo -->
                            <a href="/bicycles">
                                <span class="fa fa-shopping-cart"></span>
                                <p>daily<strong>Shop</strong> <span>Your Shopping Partner</span></p>
                            </a>
                            <!-- img based logo -->
                            <!-- <a href="index.html"><img src="img/logo.jpg" alt="logo img"></a> -->
                        </div>
                        <!-- / logo  -->

                        <!-- search box -->
                        <div class="aa-search-box">


                        <input type="text"   id="searchName" placeholder="Search here  ">
                          <label  >name</label>
                          </div>
                      <div class="aa-search-box">
                        <input type="text" id="searchStyle" placeholder="Search here  ">

                          <label  >style</label>


                        </div>
                        <!-- / search box -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- / header bottom  -->
</header>
<!-- / header section -->


<!-- menu -->
<section id="menu">
    <div class="container">
        <div class="menu-area">
            <!-- Navbar -->
            <div class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <!-- Left nav -->
                    <ul class="nav navbar-nav">

                        <li><p>items </p>

                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
    </div>
</section>
<!-- / menu -->

<%= javascript_include_tag "bicycle/custom" %>

app/views/bicycles/edit.html.erb
<%= render 'admin_pages/logout' %>
<h1>Editing Bicycle</h1>

<%= render 'form', bicycle: @bicycle %>

<%= link_to 'Show', @bicycle %> |
<%= link_to 'Back', admin_pages_index_path %>

app/views/bicycles/index.html.erb
<%= render 'header' %>


<!-- Products section -->
<section id="aa-product">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="aa-product-area">
            <div class="aa-product-inner">
              <!-- start prduct navigation -->
              <ul class="nav nav-tabs aa-products-tab">
                <li class="active"><a href="#men" data-toggle="tab">Bicycles</a></li>

              </ul>
              <!-- Tab panes -->
              <div class="tab-content">
                <!-- Start men product category -->
                <div class="tab-pane fade in active" id="men">
                  <ul class="aa-product-catg" id="searchAjax">
                    <!-- start single product item -->
                    <% @bicycles.each do |bicycle| %>
                    <li>
                      <figure>
                        <a class="aa-product-img" href="#"><img height="300" width="250" src="<%= bicycle.image_link %>" ></a>
                        <%= link_to raw('<span class="fa fa-shopping-cart"></span>View Details'), bicycle , {class: 'aa-add-card-btn'}%>

                        <figcaption>
                          <h4 class="aa-product-title"><p ><%= bicycle.name %> (<%= bicycle.style.name %> )</p></h4>
                          <span class="aa-product-price"><%= number_to_currency(bicycle.price,:delimiter => ".", :separator => ",") %></span>
                        </figcaption>
                      </figure>
                      <div class="aa-product-hvr-content">
                          <a href="#" data-toggle2="tooltip" data-placement="top" title="Quick View" data-toggle="modal" data-target="#quick-view-modal-<%= bicycle.id %>"><span class="fa fa-search"></span></a>
                      </div>

                    </li>


                        <!-- quick view modal -->
                        <div class="modal fade" id="quick-view-modal-<%= bicycle.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                          <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-body">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <div class="row">
                                  <!-- Modal view slider -->
                                  <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div class="aa-product-view-slider">
                                      <div class="simpleLens-gallery-container" id="demo-1">
                                        <div class="simpleLens-container">
                                          <div class="simpleLens-big-image-container">
                                            <a class="simpleLens-lens-image" data-lens-image="<%= bicycle.image_link %>">
                                              <img height="300" width="250" src="<%= bicycle.image_link %>" class="simpleLens-big-image">
                                            </a>
                                          </div>
                                        </div>

                                      </div>
                                    </div>
                                  </div>
                                  <!-- Modal view content -->
                                  <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div class="aa-product-view-content">
                                      <h3 style="color: #b3aeae"><%= bicycle.name %></h3>
                                      <div class="aa-price-block">
                                        <span style="color:  #ff6666" class="aa-product-view-price"><%= number_to_currency(bicycle.price,:delimiter => ".", :separator => ",") %></span>

                                      </div>
                                      <p>Click On View Details To See Description</p>


                                      <div class="aa-prod-quantity">
                                        <p class="aa-prod-category">
                                          Style: <p style="color: #ce7945"><%= bicycle.style.name %></p>
                                        </p>
                                      </div>
                                      <div class="aa-prod-view-bottom">
                                        <%= link_to 'View Details', bicycle , {class: 'aa-add-to-cart-btn'}%>

                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div><!-- /.modal-content -->
                          </div><!-- /.modal-dialog -->
                        </div><!-- / quick view modal -->
                    <% end %>

                  </ul>

                </div>
                <!-- / men product category -->

              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- / Products section -->

<%= render 'footer' %>

app/views/bicycles/new.html.erb
<%= render 'admin_pages/logout' %>
<h1>New Bicycle</h1>

<%= render 'form', bicycle: @bicycle %>

<%= link_to 'Back', admin_pages_index_path %>

app/views/bicycles/show.html.erb
<% if admin_signed_in? %>
<%= render 'admin_pages/logout' %>
<p id="notice"><%= notice %></p>

<div class="container">
  <table class="table">
    <tr>
      <th>id</th>
      <th>name</th>
      <th>price</th>
      <th>style</th>
      <th>description</th>
      <th>image link</th>
      <th>edit</th>
    </tr>

    <tr>
      <td><%= @bicycle.id %></td>
      <td><%= @bicycle.name %></td>
      <td><%= @bicycle.price %></td>
      <td><%= @bicycle.style.name %></td>
      <td><%= @bicycle.description %></td>
      <td><%= @bicycle.image_link %></td>

      <td><%= link_to 'Edit', edit_bicycle_path(@bicycle) %></td>
    </tr>
  </table>

</div>


<%= link_to 'Back', admin_pages_index_path %>

    <%else %>

   <%= render 'header' %>

    <!-- catg header banner section -->
    <section id="aa-catg-head-banner">
      <img src="<%= @bicycle.image_link %>" height="300" width="1920" alt="fashion img">
      <div class="aa-catg-head-banner-area">
        <div class="container">
          <div class="aa-catg-head-banner-content">
            <h2><%= @bicycle.name %></h2>

          </div>
        </div>
      </div>
    </section>
    <!-- / catg header banner section -->

    <!-- product category -->
    <section id="aa-product-details">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="aa-product-details-area">
              <div class="aa-product-details-content">
                <div class="row">
                  <!-- Modal view slider -->
                  <div class="col-md-5 col-sm-5 col-xs-12">
                    <div class="aa-product-view-slider">
                      <div id="demo-1" class="simpleLens-gallery-container">
                        <div class="simpleLens-container">
                          <div class="simpleLens-big-image-container"><a data-lens-image="<%=@bicycle.image_link%>" class="simpleLens-lens-image"><img src="<%=@bicycle.image_link%>" class="simpleLens-big-image"></a></div>
                        </div>

                      </div>
                    </div>
                  </div>
                  <!-- Modal view content -->
                  <div class="col-md-7 col-sm-7 col-xs-12">
                    <div class="aa-product-view-content">
                      <h3 style="color: #b3aeae"><%= @bicycle.name %></h3>
                      <div class="aa-price-block">
                        <span style="color:  #ff6666" class="aa-product-view-price"><%= number_to_currency(@bicycle.price,:delimiter => ".", :separator => ",") %></span>
                      </div>
                      <p><%= @bicycle.description %></p>


                      <div class="aa-prod-quantity">

                        <p class="aa-prod-category">
                          Style: <p style="color: #ce7945"><%= @bicycle.style.name %></p>
                        </p>
                      </div>

                    </div>
                  </div>
                </div>
              </div>



            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- / product category -->


    <%= render 'footer' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LynksTask</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


      <%= yield %>
  </body>
</html>

app/views/styles/_form.html.erb
<%= form_for(style) do |f| %>
  <% if style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.label :name %>:
    <%= f.text_field :name %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/styles/edit.html.erb
<%= render 'admin_pages/logout' %>
<h1>Editing Style</h1>

<%= render 'form', style: @style %>

<%= link_to 'Show', @style %> |
<%= link_to 'Back', admin_pages_index_path %>

app/views/styles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Styles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @styles.each do |style| %>
      <tr>
        <td><%= link_to 'Show', style %></td>
        <td><%= link_to 'Edit', edit_style_path(style) %></td>
        <td><%= link_to 'Destroy', style, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Style', new_style_path %>

app/views/styles/new.html.erb
<%= render 'admin_pages/logout' %>

<h1>New Style</h1>


<%= render 'form', style: @style %>

<%= link_to 'Back', admin_pages_index_path %>

app/views/styles/show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'admin_pages/logout' %>
<div class="container">
  <table class="table">
    <tr>
    <th>id</th>
    <th>name</th>
      <th>edit</th>
    </tr>

    <tr>
      <td><%= @style.id %></td>
      <td><%= @style.name %></td>
      <td><%= link_to 'Edit', edit_style_path(@style) %></td>
    </tr>
  </table>

</div>

 |
<%= link_to 'Back', admin_pages_index_path %>